const Actions = {
    DELETE_USER: 'DELETE_USER',
    BAN_USER: 'BAN_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_CALANDER: 'UPDATE_CALANDER',
    REMOVE_SUPER_ADMIN: 'REMOVE_SUPER_ADMIN',
    MANAGE_ROLES: 'MANAGE_ROLES',
};

export default Actions;
